# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
sal_identify_objects <- function(indat, threshold, maxobj) {
    .Call('_harpSpatial_sal_identify_objects', PACKAGE = 'harpSpatial', indat, threshold, maxobj)
}

cumsum2d <- function(indat) {
    .Call('_harpSpatial_cumsum2d', PACKAGE = 'harpSpatial', indat)
}

window_mean_from_cumsum <- function(indat, wsize) {
    .Call('_harpSpatial_window_mean_from_cumsum', PACKAGE = 'harpSpatial', indat, wsize)
}

windowMean <- function(indat, radius) {
    .Call('_harpSpatial_windowMean', PACKAGE = 'harpSpatial', indat, radius)
}

score_fss <- function(fc, ob, thresholds, window_sizes) {
    .Call('_harpSpatial_score_fss', PACKAGE = 'harpSpatial', fc, ob, thresholds, window_sizes)
}

