# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
sal_identify_objects <- function(indat, threshold, maxobj) {
    .Call('_harpSpatial_sal_identify_objects', PACKAGE = 'harpSpatial', indat, threshold, maxobj)
}

cumsum2d <- function(indat) {
    .Call('_harpSpatial_cumsum2d', PACKAGE = 'harpSpatial', indat)
}

windowMeanFromCumsum <- function(indat, radius) {
    .Call('_harpSpatial_windowMeanFromCumsum', PACKAGE = 'harpSpatial', indat, radius)
}

windowMean <- function(indat, radius) {
    .Call('_harpSpatial_windowMean', PACKAGE = 'harpSpatial', indat, radius)
}

